// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PHTmessage.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "PHTmessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PHT {

namespace {

const ::google::protobuf::Descriptor* PHTmessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PHTmessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_PHTmessage_2eproto() {
  protobuf_AddDesc_PHTmessage_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "PHTmessage.proto");
  GOOGLE_CHECK(file != NULL);
  PHTmessage_descriptor_ = file->message_type(0);
  static const int PHTmessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PHTmessage, proposal_),
  };
  PHTmessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PHTmessage_descriptor_,
      PHTmessage::default_instance_,
      PHTmessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PHTmessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PHTmessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PHTmessage));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_PHTmessage_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PHTmessage_descriptor_, &PHTmessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_PHTmessage_2eproto() {
  delete PHTmessage::default_instance_;
  delete PHTmessage_reflection_;
}

void protobuf_AddDesc_PHTmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_Proposals_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\020PHTmessage.proto\022\003PHT\032\017Proposals.proto"
    "\"*\n\nPHTmessage\022\034\n\010proposal\030\001 \003(\0132\n.Propo"
    "sals", 84);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "PHTmessage.proto", &protobuf_RegisterTypes);
  PHTmessage::default_instance_ = new PHTmessage();
  PHTmessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_PHTmessage_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_PHTmessage_2eproto {
  StaticDescriptorInitializer_PHTmessage_2eproto() {
    protobuf_AddDesc_PHTmessage_2eproto();
  }
} static_descriptor_initializer_PHTmessage_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PHTmessage::kProposalFieldNumber;
#endif  // !_MSC_VER

PHTmessage::PHTmessage()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PHT.PHTmessage)
}

void PHTmessage::InitAsDefaultInstance() {
}

PHTmessage::PHTmessage(const PHTmessage& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PHT.PHTmessage)
}

void PHTmessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PHTmessage::~PHTmessage() {
  // @@protoc_insertion_point(destructor:PHT.PHTmessage)
  SharedDtor();
}

void PHTmessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PHTmessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PHTmessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PHTmessage_descriptor_;
}

const PHTmessage& PHTmessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_PHTmessage_2eproto();
  return *default_instance_;
}

PHTmessage* PHTmessage::default_instance_ = NULL;

PHTmessage* PHTmessage::New() const {
  return new PHTmessage;
}

void PHTmessage::Clear() {
  proposal_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PHTmessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PHT.PHTmessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Proposals proposal = 1;
      case 1: {
        if (tag == 10) {
         parse_proposal:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_proposal()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_proposal;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PHT.PHTmessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PHT.PHTmessage)
  return false;
#undef DO_
}

void PHTmessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PHT.PHTmessage)
  // repeated .Proposals proposal = 1;
  for (int i = 0; i < this->proposal_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->proposal(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PHT.PHTmessage)
}

::google::protobuf::uint8* PHTmessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PHT.PHTmessage)
  // repeated .Proposals proposal = 1;
  for (int i = 0; i < this->proposal_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->proposal(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PHT.PHTmessage)
  return target;
}

int PHTmessage::ByteSize() const {
  int total_size = 0;

  // repeated .Proposals proposal = 1;
  total_size += 1 * this->proposal_size();
  for (int i = 0; i < this->proposal_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->proposal(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PHTmessage::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PHTmessage* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PHTmessage*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PHTmessage::MergeFrom(const PHTmessage& from) {
  GOOGLE_CHECK_NE(&from, this);
  proposal_.MergeFrom(from.proposal_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PHTmessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PHTmessage::CopyFrom(const PHTmessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PHTmessage::IsInitialized() const {

  return true;
}

void PHTmessage::Swap(PHTmessage* other) {
  if (other != this) {
    proposal_.Swap(&other->proposal_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PHTmessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PHTmessage_descriptor_;
  metadata.reflection = PHTmessage_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PHT

// @@protoc_insertion_point(global_scope)
