// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProposalStatus.proto

package PHT;

public final class ProposalStatusOuterClass {
  private ProposalStatusOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code PHT.ProposalStatus}
   */
  public enum ProposalStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Draft = 0;</code>
     */
    Draft(0, 0),
    /**
     * <code>Accepted = 1;</code>
     */
    Accepted(1, 1),
    /**
     * <code>Rejected = 2;</code>
     */
    Rejected(2, 2),
    /**
     * <code>Submitted = 3;</code>
     */
    Submitted(3, 3),
    /**
     * <code>Merged = 4;</code>
     */
    Merged(4, 4),
    ;

    /**
     * <code>Draft = 0;</code>
     */
    public static final int Draft_VALUE = 0;
    /**
     * <code>Accepted = 1;</code>
     */
    public static final int Accepted_VALUE = 1;
    /**
     * <code>Rejected = 2;</code>
     */
    public static final int Rejected_VALUE = 2;
    /**
     * <code>Submitted = 3;</code>
     */
    public static final int Submitted_VALUE = 3;
    /**
     * <code>Merged = 4;</code>
     */
    public static final int Merged_VALUE = 4;


    public final int getNumber() { return value; }

    public static ProposalStatus valueOf(int value) {
      switch (value) {
        case 0: return Draft;
        case 1: return Accepted;
        case 2: return Rejected;
        case 3: return Submitted;
        case 4: return Merged;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProposalStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProposalStatus>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProposalStatus>() {
            public ProposalStatus findValueByNumber(int number) {
              return ProposalStatus.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PHT.ProposalStatusOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProposalStatus[] VALUES = values();

    public static ProposalStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProposalStatus(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PHT.ProposalStatus)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProposalStatus.proto\022\003PHT*R\n\016ProposalS" +
      "tatus\022\t\n\005Draft\020\000\022\014\n\010Accepted\020\001\022\014\n\010Reject" +
      "ed\020\002\022\r\n\tSubmitted\020\003\022\n\n\006Merged\020\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
