// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TACReviews.proto

package PHT;

public final class TACReviewsOuterClass {
  private TACReviewsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TACReviewsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.TACReviews)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string comments = 1;</code>
     */
    boolean hasComments();
    /**
     * <code>optional string comments = 1;</code>
     */
    java.lang.String getComments();
    /**
     * <code>optional string comments = 1;</code>
     */
    com.google.protobuf.ByteString
        getCommentsBytes();

    /**
     * <code>optional string final_grade = 2;</code>
     */
    boolean hasFinalGrade();
    /**
     * <code>optional string final_grade = 2;</code>
     */
    java.lang.String getFinalGrade();
    /**
     * <code>optional string final_grade = 2;</code>
     */
    com.google.protobuf.ByteString
        getFinalGradeBytes();

    /**
     * <code>optional int64 tac_id = 3;</code>
     */
    boolean hasTacId();
    /**
     * <code>optional int64 tac_id = 3;</code>
     */
    long getTacId();
  }
  /**
   * Protobuf type {@code PHT.TACReviews}
   */
  public static final class TACReviews extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.TACReviews)
      TACReviewsOrBuilder {
    // Use TACReviews.newBuilder() to construct.
    private TACReviews(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TACReviews(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TACReviews defaultInstance;
    public static TACReviews getDefaultInstance() {
      return defaultInstance;
    }

    public TACReviews getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TACReviews(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              comments_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              finalGrade_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              tacId_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.TACReviewsOuterClass.internal_static_PHT_TACReviews_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.TACReviewsOuterClass.internal_static_PHT_TACReviews_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.TACReviewsOuterClass.TACReviews.class, PHT.TACReviewsOuterClass.TACReviews.Builder.class);
    }

    public static com.google.protobuf.Parser<TACReviews> PARSER =
        new com.google.protobuf.AbstractParser<TACReviews>() {
      public TACReviews parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TACReviews(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TACReviews> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int COMMENTS_FIELD_NUMBER = 1;
    private java.lang.Object comments_;
    /**
     * <code>optional string comments = 1;</code>
     */
    public boolean hasComments() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string comments = 1;</code>
     */
    public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          comments_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string comments = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FINAL_GRADE_FIELD_NUMBER = 2;
    private java.lang.Object finalGrade_;
    /**
     * <code>optional string final_grade = 2;</code>
     */
    public boolean hasFinalGrade() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string final_grade = 2;</code>
     */
    public java.lang.String getFinalGrade() {
      java.lang.Object ref = finalGrade_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          finalGrade_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string final_grade = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFinalGradeBytes() {
      java.lang.Object ref = finalGrade_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        finalGrade_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAC_ID_FIELD_NUMBER = 3;
    private long tacId_;
    /**
     * <code>optional int64 tac_id = 3;</code>
     */
    public boolean hasTacId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 tac_id = 3;</code>
     */
    public long getTacId() {
      return tacId_;
    }

    private void initFields() {
      comments_ = "";
      finalGrade_ = "";
      tacId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCommentsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFinalGradeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, tacId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCommentsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFinalGradeBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, tacId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.TACReviewsOuterClass.TACReviews parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.TACReviewsOuterClass.TACReviews prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.TACReviews}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.TACReviews)
        PHT.TACReviewsOuterClass.TACReviewsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.TACReviewsOuterClass.internal_static_PHT_TACReviews_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.TACReviewsOuterClass.internal_static_PHT_TACReviews_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.TACReviewsOuterClass.TACReviews.class, PHT.TACReviewsOuterClass.TACReviews.Builder.class);
      }

      // Construct using PHT.TACReviewsOuterClass.TACReviews.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        comments_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        finalGrade_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        tacId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.TACReviewsOuterClass.internal_static_PHT_TACReviews_descriptor;
      }

      public PHT.TACReviewsOuterClass.TACReviews getDefaultInstanceForType() {
        return PHT.TACReviewsOuterClass.TACReviews.getDefaultInstance();
      }

      public PHT.TACReviewsOuterClass.TACReviews build() {
        PHT.TACReviewsOuterClass.TACReviews result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.TACReviewsOuterClass.TACReviews buildPartial() {
        PHT.TACReviewsOuterClass.TACReviews result = new PHT.TACReviewsOuterClass.TACReviews(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.comments_ = comments_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.finalGrade_ = finalGrade_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.tacId_ = tacId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.TACReviewsOuterClass.TACReviews) {
          return mergeFrom((PHT.TACReviewsOuterClass.TACReviews)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.TACReviewsOuterClass.TACReviews other) {
        if (other == PHT.TACReviewsOuterClass.TACReviews.getDefaultInstance()) return this;
        if (other.hasComments()) {
          bitField0_ |= 0x00000001;
          comments_ = other.comments_;
          onChanged();
        }
        if (other.hasFinalGrade()) {
          bitField0_ |= 0x00000002;
          finalGrade_ = other.finalGrade_;
          onChanged();
        }
        if (other.hasTacId()) {
          setTacId(other.getTacId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.TACReviewsOuterClass.TACReviews parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.TACReviewsOuterClass.TACReviews) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object comments_ = "";
      /**
       * <code>optional string comments = 1;</code>
       */
      public boolean hasComments() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string comments = 1;</code>
       */
      public java.lang.String getComments() {
        java.lang.Object ref = comments_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            comments_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string comments = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCommentsBytes() {
        java.lang.Object ref = comments_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          comments_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string comments = 1;</code>
       */
      public Builder setComments(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        comments_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string comments = 1;</code>
       */
      public Builder clearComments() {
        bitField0_ = (bitField0_ & ~0x00000001);
        comments_ = getDefaultInstance().getComments();
        onChanged();
        return this;
      }
      /**
       * <code>optional string comments = 1;</code>
       */
      public Builder setCommentsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        comments_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object finalGrade_ = "";
      /**
       * <code>optional string final_grade = 2;</code>
       */
      public boolean hasFinalGrade() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string final_grade = 2;</code>
       */
      public java.lang.String getFinalGrade() {
        java.lang.Object ref = finalGrade_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            finalGrade_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string final_grade = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFinalGradeBytes() {
        java.lang.Object ref = finalGrade_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          finalGrade_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string final_grade = 2;</code>
       */
      public Builder setFinalGrade(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        finalGrade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string final_grade = 2;</code>
       */
      public Builder clearFinalGrade() {
        bitField0_ = (bitField0_ & ~0x00000002);
        finalGrade_ = getDefaultInstance().getFinalGrade();
        onChanged();
        return this;
      }
      /**
       * <code>optional string final_grade = 2;</code>
       */
      public Builder setFinalGradeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        finalGrade_ = value;
        onChanged();
        return this;
      }

      private long tacId_ ;
      /**
       * <code>optional int64 tac_id = 3;</code>
       */
      public boolean hasTacId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 tac_id = 3;</code>
       */
      public long getTacId() {
        return tacId_;
      }
      /**
       * <code>optional int64 tac_id = 3;</code>
       */
      public Builder setTacId(long value) {
        bitField0_ |= 0x00000004;
        tacId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 tac_id = 3;</code>
       */
      public Builder clearTacId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        tacId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PHT.TACReviews)
    }

    static {
      defaultInstance = new TACReviews(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.TACReviews)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_TACReviews_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_TACReviews_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020TACReviews.proto\022\003PHT\"C\n\nTACReviews\022\020\n" +
      "\010comments\030\001 \001(\t\022\023\n\013final_grade\030\002 \001(\t\022\016\n\006" +
      "tac_id\030\003 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PHT_TACReviews_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PHT_TACReviews_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_TACReviews_descriptor,
        new java.lang.String[] { "Comments", "FinalGrade", "TacId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
