all: example.class apioda.class

example.class: example.java
	javac example.java

apioda.class: apioda.java
	javac apioda.java

.PHONY: clean cleanall

clean:
	rm -rf *.class

cleanall: 
	rm -rf *.class
	rm -rf PHT/*.class


