// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoAuthors.proto

package PHT;

public final class CoAuthorsOuterClass {
  private CoAuthorsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CoAuthorsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.CoAuthors)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 author_id = 1;</code>
     */
    boolean hasAuthorId();
    /**
     * <code>optional int64 author_id = 1;</code>
     */
    long getAuthorId();

    /**
     * <code>optional int64 coAuthorsID = 2;</code>
     *
     * <pre>
     *optional int64 proposal_id = 3;
     * </pre>
     */
    boolean hasCoAuthorsID();
    /**
     * <code>optional int64 coAuthorsID = 2;</code>
     *
     * <pre>
     *optional int64 proposal_id = 3;
     * </pre>
     */
    long getCoAuthorsID();
  }
  /**
   * Protobuf type {@code PHT.CoAuthors}
   */
  public static final class CoAuthors extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.CoAuthors)
      CoAuthorsOrBuilder {
    // Use CoAuthors.newBuilder() to construct.
    private CoAuthors(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CoAuthors(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CoAuthors defaultInstance;
    public static CoAuthors getDefaultInstance() {
      return defaultInstance;
    }

    public CoAuthors getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CoAuthors(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              authorId_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              coAuthorsID_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.CoAuthorsOuterClass.internal_static_PHT_CoAuthors_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.CoAuthorsOuterClass.internal_static_PHT_CoAuthors_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.CoAuthorsOuterClass.CoAuthors.class, PHT.CoAuthorsOuterClass.CoAuthors.Builder.class);
    }

    public static com.google.protobuf.Parser<CoAuthors> PARSER =
        new com.google.protobuf.AbstractParser<CoAuthors>() {
      public CoAuthors parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CoAuthors(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CoAuthors> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int AUTHOR_ID_FIELD_NUMBER = 1;
    private long authorId_;
    /**
     * <code>optional int64 author_id = 1;</code>
     */
    public boolean hasAuthorId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 author_id = 1;</code>
     */
    public long getAuthorId() {
      return authorId_;
    }

    public static final int COAUTHORSID_FIELD_NUMBER = 2;
    private long coAuthorsID_;
    /**
     * <code>optional int64 coAuthorsID = 2;</code>
     *
     * <pre>
     *optional int64 proposal_id = 3;
     * </pre>
     */
    public boolean hasCoAuthorsID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 coAuthorsID = 2;</code>
     *
     * <pre>
     *optional int64 proposal_id = 3;
     * </pre>
     */
    public long getCoAuthorsID() {
      return coAuthorsID_;
    }

    private void initFields() {
      authorId_ = 0L;
      coAuthorsID_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, authorId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, coAuthorsID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, authorId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, coAuthorsID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.CoAuthorsOuterClass.CoAuthors parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.CoAuthorsOuterClass.CoAuthors prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.CoAuthors}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.CoAuthors)
        PHT.CoAuthorsOuterClass.CoAuthorsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.CoAuthorsOuterClass.internal_static_PHT_CoAuthors_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.CoAuthorsOuterClass.internal_static_PHT_CoAuthors_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.CoAuthorsOuterClass.CoAuthors.class, PHT.CoAuthorsOuterClass.CoAuthors.Builder.class);
      }

      // Construct using PHT.CoAuthorsOuterClass.CoAuthors.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        authorId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        coAuthorsID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.CoAuthorsOuterClass.internal_static_PHT_CoAuthors_descriptor;
      }

      public PHT.CoAuthorsOuterClass.CoAuthors getDefaultInstanceForType() {
        return PHT.CoAuthorsOuterClass.CoAuthors.getDefaultInstance();
      }

      public PHT.CoAuthorsOuterClass.CoAuthors build() {
        PHT.CoAuthorsOuterClass.CoAuthors result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.CoAuthorsOuterClass.CoAuthors buildPartial() {
        PHT.CoAuthorsOuterClass.CoAuthors result = new PHT.CoAuthorsOuterClass.CoAuthors(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.authorId_ = authorId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.coAuthorsID_ = coAuthorsID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.CoAuthorsOuterClass.CoAuthors) {
          return mergeFrom((PHT.CoAuthorsOuterClass.CoAuthors)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.CoAuthorsOuterClass.CoAuthors other) {
        if (other == PHT.CoAuthorsOuterClass.CoAuthors.getDefaultInstance()) return this;
        if (other.hasAuthorId()) {
          setAuthorId(other.getAuthorId());
        }
        if (other.hasCoAuthorsID()) {
          setCoAuthorsID(other.getCoAuthorsID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.CoAuthorsOuterClass.CoAuthors parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.CoAuthorsOuterClass.CoAuthors) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long authorId_ ;
      /**
       * <code>optional int64 author_id = 1;</code>
       */
      public boolean hasAuthorId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 author_id = 1;</code>
       */
      public long getAuthorId() {
        return authorId_;
      }
      /**
       * <code>optional int64 author_id = 1;</code>
       */
      public Builder setAuthorId(long value) {
        bitField0_ |= 0x00000001;
        authorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 author_id = 1;</code>
       */
      public Builder clearAuthorId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        authorId_ = 0L;
        onChanged();
        return this;
      }

      private long coAuthorsID_ ;
      /**
       * <code>optional int64 coAuthorsID = 2;</code>
       *
       * <pre>
       *optional int64 proposal_id = 3;
       * </pre>
       */
      public boolean hasCoAuthorsID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 coAuthorsID = 2;</code>
       *
       * <pre>
       *optional int64 proposal_id = 3;
       * </pre>
       */
      public long getCoAuthorsID() {
        return coAuthorsID_;
      }
      /**
       * <code>optional int64 coAuthorsID = 2;</code>
       *
       * <pre>
       *optional int64 proposal_id = 3;
       * </pre>
       */
      public Builder setCoAuthorsID(long value) {
        bitField0_ |= 0x00000002;
        coAuthorsID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 coAuthorsID = 2;</code>
       *
       * <pre>
       *optional int64 proposal_id = 3;
       * </pre>
       */
      public Builder clearCoAuthorsID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        coAuthorsID_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PHT.CoAuthors)
    }

    static {
      defaultInstance = new CoAuthors(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.CoAuthors)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_CoAuthors_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_CoAuthors_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017CoAuthors.proto\022\003PHT\"3\n\tCoAuthors\022\021\n\ta" +
      "uthor_id\030\001 \001(\003\022\023\n\013coAuthorsID\030\002 \001(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PHT_CoAuthors_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PHT_CoAuthors_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_CoAuthors_descriptor,
        new java.lang.String[] { "AuthorId", "CoAuthorsID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
