// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PHTmessage.proto

package PHT;

public final class PHTmessageOuterClass {
  private PHTmessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AnswerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.Answer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string answer = 1;</code>
     */
    boolean hasAnswer();
    /**
     * <code>optional string answer = 1;</code>
     */
    java.lang.String getAnswer();
    /**
     * <code>optional string answer = 1;</code>
     */
    com.google.protobuf.ByteString
        getAnswerBytes();
  }
  /**
   * Protobuf type {@code PHT.Answer}
   */
  public static final class Answer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.Answer)
      AnswerOrBuilder {
    // Use Answer.newBuilder() to construct.
    private Answer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Answer(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Answer defaultInstance;
    public static Answer getDefaultInstance() {
      return defaultInstance;
    }

    public Answer getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Answer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              answer_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.PHTmessageOuterClass.internal_static_PHT_Answer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.PHTmessageOuterClass.internal_static_PHT_Answer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.PHTmessageOuterClass.Answer.class, PHT.PHTmessageOuterClass.Answer.Builder.class);
    }

    public static com.google.protobuf.Parser<Answer> PARSER =
        new com.google.protobuf.AbstractParser<Answer>() {
      public Answer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Answer(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Answer> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ANSWER_FIELD_NUMBER = 1;
    private java.lang.Object answer_;
    /**
     * <code>optional string answer = 1;</code>
     */
    public boolean hasAnswer() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string answer = 1;</code>
     */
    public java.lang.String getAnswer() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          answer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string answer = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnswerBytes() {
      java.lang.Object ref = answer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        answer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      answer_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getAnswerBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getAnswerBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.PHTmessageOuterClass.Answer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Answer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.PHTmessageOuterClass.Answer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.PHTmessageOuterClass.Answer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.PHTmessageOuterClass.Answer prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.Answer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.Answer)
        PHT.PHTmessageOuterClass.AnswerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_Answer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_Answer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.PHTmessageOuterClass.Answer.class, PHT.PHTmessageOuterClass.Answer.Builder.class);
      }

      // Construct using PHT.PHTmessageOuterClass.Answer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        answer_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_Answer_descriptor;
      }

      public PHT.PHTmessageOuterClass.Answer getDefaultInstanceForType() {
        return PHT.PHTmessageOuterClass.Answer.getDefaultInstance();
      }

      public PHT.PHTmessageOuterClass.Answer build() {
        PHT.PHTmessageOuterClass.Answer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.PHTmessageOuterClass.Answer buildPartial() {
        PHT.PHTmessageOuterClass.Answer result = new PHT.PHTmessageOuterClass.Answer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.answer_ = answer_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.PHTmessageOuterClass.Answer) {
          return mergeFrom((PHT.PHTmessageOuterClass.Answer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.PHTmessageOuterClass.Answer other) {
        if (other == PHT.PHTmessageOuterClass.Answer.getDefaultInstance()) return this;
        if (other.hasAnswer()) {
          bitField0_ |= 0x00000001;
          answer_ = other.answer_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.PHTmessageOuterClass.Answer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.PHTmessageOuterClass.Answer) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object answer_ = "";
      /**
       * <code>optional string answer = 1;</code>
       */
      public boolean hasAnswer() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string answer = 1;</code>
       */
      public java.lang.String getAnswer() {
        java.lang.Object ref = answer_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            answer_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string answer = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAnswerBytes() {
        java.lang.Object ref = answer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          answer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string answer = 1;</code>
       */
      public Builder setAnswer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        answer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string answer = 1;</code>
       */
      public Builder clearAnswer() {
        bitField0_ = (bitField0_ & ~0x00000001);
        answer_ = getDefaultInstance().getAnswer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string answer = 1;</code>
       */
      public Builder setAnswerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        answer_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PHT.Answer)
    }

    static {
      defaultInstance = new Answer(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.Answer)
  }

  public interface QueryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.Query)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 query = 1;</code>
     */
    boolean hasQuery();
    /**
     * <code>optional int64 query = 1;</code>
     */
    long getQuery();

    /**
     * <code>optional bool file_to_upload = 2 [default = false];</code>
     */
    boolean hasFileToUpload();
    /**
     * <code>optional bool file_to_upload = 2 [default = false];</code>
     */
    boolean getFileToUpload();

    /**
     * <code>optional string file_name = 3;</code>
     */
    boolean hasFileName();
    /**
     * <code>optional string file_name = 3;</code>
     */
    java.lang.String getFileName();
    /**
     * <code>optional string file_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getFileNameBytes();

    /**
     * <code>optional bytes file_data = 4;</code>
     */
    boolean hasFileData();
    /**
     * <code>optional bytes file_data = 4;</code>
     */
    com.google.protobuf.ByteString getFileData();

    /**
     * <code>optional bool delete_file = 5 [default = false];</code>
     */
    boolean hasDeleteFile();
    /**
     * <code>optional bool delete_file = 5 [default = false];</code>
     */
    boolean getDeleteFile();
  }
  /**
   * Protobuf type {@code PHT.Query}
   */
  public static final class Query extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.Query)
      QueryOrBuilder {
    // Use Query.newBuilder() to construct.
    private Query(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Query(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Query defaultInstance;
    public static Query getDefaultInstance() {
      return defaultInstance;
    }

    public Query getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Query(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              query_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              fileToUpload_ = input.readBool();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              fileName_ = bs;
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fileData_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              deleteFile_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.PHTmessageOuterClass.internal_static_PHT_Query_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.PHTmessageOuterClass.internal_static_PHT_Query_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.PHTmessageOuterClass.Query.class, PHT.PHTmessageOuterClass.Query.Builder.class);
    }

    public static com.google.protobuf.Parser<Query> PARSER =
        new com.google.protobuf.AbstractParser<Query>() {
      public Query parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Query(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Query> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int QUERY_FIELD_NUMBER = 1;
    private long query_;
    /**
     * <code>optional int64 query = 1;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 query = 1;</code>
     */
    public long getQuery() {
      return query_;
    }

    public static final int FILE_TO_UPLOAD_FIELD_NUMBER = 2;
    private boolean fileToUpload_;
    /**
     * <code>optional bool file_to_upload = 2 [default = false];</code>
     */
    public boolean hasFileToUpload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool file_to_upload = 2 [default = false];</code>
     */
    public boolean getFileToUpload() {
      return fileToUpload_;
    }

    public static final int FILE_NAME_FIELD_NUMBER = 3;
    private java.lang.Object fileName_;
    /**
     * <code>optional string file_name = 3;</code>
     */
    public boolean hasFileName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string file_name = 3;</code>
     */
    public java.lang.String getFileName() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fileName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string file_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFileNameBytes() {
      java.lang.Object ref = fileName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILE_DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString fileData_;
    /**
     * <code>optional bytes file_data = 4;</code>
     */
    public boolean hasFileData() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bytes file_data = 4;</code>
     */
    public com.google.protobuf.ByteString getFileData() {
      return fileData_;
    }

    public static final int DELETE_FILE_FIELD_NUMBER = 5;
    private boolean deleteFile_;
    /**
     * <code>optional bool delete_file = 5 [default = false];</code>
     */
    public boolean hasDeleteFile() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool delete_file = 5 [default = false];</code>
     */
    public boolean getDeleteFile() {
      return deleteFile_;
    }

    private void initFields() {
      query_ = 0L;
      fileToUpload_ = false;
      fileName_ = "";
      fileData_ = com.google.protobuf.ByteString.EMPTY;
      deleteFile_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, fileToUpload_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, fileData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, deleteFile_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, query_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, fileToUpload_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getFileNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, fileData_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, deleteFile_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.PHTmessageOuterClass.Query parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Query parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.PHTmessageOuterClass.Query parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.PHTmessageOuterClass.Query parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.PHTmessageOuterClass.Query prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.Query}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.Query)
        PHT.PHTmessageOuterClass.QueryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_Query_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_Query_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.PHTmessageOuterClass.Query.class, PHT.PHTmessageOuterClass.Query.Builder.class);
      }

      // Construct using PHT.PHTmessageOuterClass.Query.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        query_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        fileToUpload_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        fileName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fileData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        deleteFile_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_Query_descriptor;
      }

      public PHT.PHTmessageOuterClass.Query getDefaultInstanceForType() {
        return PHT.PHTmessageOuterClass.Query.getDefaultInstance();
      }

      public PHT.PHTmessageOuterClass.Query build() {
        PHT.PHTmessageOuterClass.Query result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.PHTmessageOuterClass.Query buildPartial() {
        PHT.PHTmessageOuterClass.Query result = new PHT.PHTmessageOuterClass.Query(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.query_ = query_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.fileToUpload_ = fileToUpload_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.fileName_ = fileName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fileData_ = fileData_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deleteFile_ = deleteFile_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.PHTmessageOuterClass.Query) {
          return mergeFrom((PHT.PHTmessageOuterClass.Query)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.PHTmessageOuterClass.Query other) {
        if (other == PHT.PHTmessageOuterClass.Query.getDefaultInstance()) return this;
        if (other.hasQuery()) {
          setQuery(other.getQuery());
        }
        if (other.hasFileToUpload()) {
          setFileToUpload(other.getFileToUpload());
        }
        if (other.hasFileName()) {
          bitField0_ |= 0x00000004;
          fileName_ = other.fileName_;
          onChanged();
        }
        if (other.hasFileData()) {
          setFileData(other.getFileData());
        }
        if (other.hasDeleteFile()) {
          setDeleteFile(other.getDeleteFile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.PHTmessageOuterClass.Query parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.PHTmessageOuterClass.Query) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long query_ ;
      /**
       * <code>optional int64 query = 1;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 query = 1;</code>
       */
      public long getQuery() {
        return query_;
      }
      /**
       * <code>optional int64 query = 1;</code>
       */
      public Builder setQuery(long value) {
        bitField0_ |= 0x00000001;
        query_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 query = 1;</code>
       */
      public Builder clearQuery() {
        bitField0_ = (bitField0_ & ~0x00000001);
        query_ = 0L;
        onChanged();
        return this;
      }

      private boolean fileToUpload_ ;
      /**
       * <code>optional bool file_to_upload = 2 [default = false];</code>
       */
      public boolean hasFileToUpload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool file_to_upload = 2 [default = false];</code>
       */
      public boolean getFileToUpload() {
        return fileToUpload_;
      }
      /**
       * <code>optional bool file_to_upload = 2 [default = false];</code>
       */
      public Builder setFileToUpload(boolean value) {
        bitField0_ |= 0x00000002;
        fileToUpload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool file_to_upload = 2 [default = false];</code>
       */
      public Builder clearFileToUpload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        fileToUpload_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object fileName_ = "";
      /**
       * <code>optional string file_name = 3;</code>
       */
      public boolean hasFileName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string file_name = 3;</code>
       */
      public java.lang.String getFileName() {
        java.lang.Object ref = fileName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fileName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string file_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFileNameBytes() {
        java.lang.Object ref = fileName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string file_name = 3;</code>
       */
      public Builder setFileName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fileName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_name = 3;</code>
       */
      public Builder clearFileName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fileName_ = getDefaultInstance().getFileName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string file_name = 3;</code>
       */
      public Builder setFileNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        fileName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString fileData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes file_data = 4;</code>
       */
      public boolean hasFileData() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes file_data = 4;</code>
       */
      public com.google.protobuf.ByteString getFileData() {
        return fileData_;
      }
      /**
       * <code>optional bytes file_data = 4;</code>
       */
      public Builder setFileData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fileData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes file_data = 4;</code>
       */
      public Builder clearFileData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fileData_ = getDefaultInstance().getFileData();
        onChanged();
        return this;
      }

      private boolean deleteFile_ ;
      /**
       * <code>optional bool delete_file = 5 [default = false];</code>
       */
      public boolean hasDeleteFile() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool delete_file = 5 [default = false];</code>
       */
      public boolean getDeleteFile() {
        return deleteFile_;
      }
      /**
       * <code>optional bool delete_file = 5 [default = false];</code>
       */
      public Builder setDeleteFile(boolean value) {
        bitField0_ |= 0x00000010;
        deleteFile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool delete_file = 5 [default = false];</code>
       */
      public Builder clearDeleteFile() {
        bitField0_ = (bitField0_ & ~0x00000010);
        deleteFile_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PHT.Query)
    }

    static {
      defaultInstance = new Query(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.Query)
  }

  public interface PHTmessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.PHTmessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
     */
    PHT.PHTmessageOuterClass.PHTmessage.MessageType getType();

    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    java.util.List<PHT.ProposalsOuterClass.Proposals> 
        getProposalList();
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    PHT.ProposalsOuterClass.Proposals getProposal(int index);
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    int getProposalCount();
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    java.util.List<? extends PHT.ProposalsOuterClass.ProposalsOrBuilder> 
        getProposalOrBuilderList();
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    PHT.ProposalsOuterClass.ProposalsOrBuilder getProposalOrBuilder(
        int index);

    /**
     * <code>optional .PHT.Query query = 3;</code>
     */
    boolean hasQuery();
    /**
     * <code>optional .PHT.Query query = 3;</code>
     */
    PHT.PHTmessageOuterClass.Query getQuery();
    /**
     * <code>optional .PHT.Query query = 3;</code>
     */
    PHT.PHTmessageOuterClass.QueryOrBuilder getQueryOrBuilder();

    /**
     * <code>optional .PHT.Answer answer = 4;</code>
     *
     * <pre>
     *repeated Column column = 5;
     * </pre>
     */
    boolean hasAnswer();
    /**
     * <code>optional .PHT.Answer answer = 4;</code>
     *
     * <pre>
     *repeated Column column = 5;
     * </pre>
     */
    PHT.PHTmessageOuterClass.Answer getAnswer();
    /**
     * <code>optional .PHT.Answer answer = 4;</code>
     *
     * <pre>
     *repeated Column column = 5;
     * </pre>
     */
    PHT.PHTmessageOuterClass.AnswerOrBuilder getAnswerOrBuilder();
  }
  /**
   * Protobuf type {@code PHT.PHTmessage}
   */
  public static final class PHTmessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.PHTmessage)
      PHTmessageOrBuilder {
    // Use PHTmessage.newBuilder() to construct.
    private PHTmessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PHTmessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PHTmessage defaultInstance;
    public static PHTmessage getDefaultInstance() {
      return defaultInstance;
    }

    public PHTmessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PHTmessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              PHT.PHTmessageOuterClass.PHTmessage.MessageType value = PHT.PHTmessageOuterClass.PHTmessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                proposal_ = new java.util.ArrayList<PHT.ProposalsOuterClass.Proposals>();
                mutable_bitField0_ |= 0x00000002;
              }
              proposal_.add(input.readMessage(PHT.ProposalsOuterClass.Proposals.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              PHT.PHTmessageOuterClass.Query.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = query_.toBuilder();
              }
              query_ = input.readMessage(PHT.PHTmessageOuterClass.Query.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(query_);
                query_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 34: {
              PHT.PHTmessageOuterClass.Answer.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = answer_.toBuilder();
              }
              answer_ = input.readMessage(PHT.PHTmessageOuterClass.Answer.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(answer_);
                answer_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          proposal_ = java.util.Collections.unmodifiableList(proposal_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.PHTmessageOuterClass.internal_static_PHT_PHTmessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.PHTmessageOuterClass.internal_static_PHT_PHTmessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.PHTmessageOuterClass.PHTmessage.class, PHT.PHTmessageOuterClass.PHTmessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PHTmessage> PARSER =
        new com.google.protobuf.AbstractParser<PHTmessage>() {
      public PHTmessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PHTmessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PHTmessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code PHT.PHTmessage.MessageType}
     */
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DATA = 1;</code>
       */
      DATA(0, 1),
      /**
       * <code>QUERY = 2;</code>
       */
      QUERY(1, 2),
      /**
       * <code>ANSWER = 3;</code>
       */
      ANSWER(2, 3),
      /**
       * <code>ERROR = 4;</code>
       */
      ERROR(3, 4),
      /**
       * <code>PST = 5;</code>
       */
      PST(4, 5),
      ;

      /**
       * <code>DATA = 1;</code>
       */
      public static final int DATA_VALUE = 1;
      /**
       * <code>QUERY = 2;</code>
       */
      public static final int QUERY_VALUE = 2;
      /**
       * <code>ANSWER = 3;</code>
       */
      public static final int ANSWER_VALUE = 3;
      /**
       * <code>ERROR = 4;</code>
       */
      public static final int ERROR_VALUE = 4;
      /**
       * <code>PST = 5;</code>
       */
      public static final int PST_VALUE = 5;


      public final int getNumber() { return value; }

      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return DATA;
          case 2: return QUERY;
          case 3: return ANSWER;
          case 4: return ERROR;
          case 5: return PST;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PHT.PHTmessageOuterClass.PHTmessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageType[] VALUES = values();

      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PHT.PHTmessage.MessageType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private PHT.PHTmessageOuterClass.PHTmessage.MessageType type_;
    /**
     * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
     */
    public PHT.PHTmessageOuterClass.PHTmessage.MessageType getType() {
      return type_;
    }

    public static final int PROPOSAL_FIELD_NUMBER = 2;
    private java.util.List<PHT.ProposalsOuterClass.Proposals> proposal_;
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    public java.util.List<PHT.ProposalsOuterClass.Proposals> getProposalList() {
      return proposal_;
    }
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    public java.util.List<? extends PHT.ProposalsOuterClass.ProposalsOrBuilder> 
        getProposalOrBuilderList() {
      return proposal_;
    }
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    public int getProposalCount() {
      return proposal_.size();
    }
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    public PHT.ProposalsOuterClass.Proposals getProposal(int index) {
      return proposal_.get(index);
    }
    /**
     * <code>repeated .PHT.Proposals proposal = 2;</code>
     *
     * <pre>
     *optional Proposals proposal = 2;
     * </pre>
     */
    public PHT.ProposalsOuterClass.ProposalsOrBuilder getProposalOrBuilder(
        int index) {
      return proposal_.get(index);
    }

    public static final int QUERY_FIELD_NUMBER = 3;
    private PHT.PHTmessageOuterClass.Query query_;
    /**
     * <code>optional .PHT.Query query = 3;</code>
     */
    public boolean hasQuery() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .PHT.Query query = 3;</code>
     */
    public PHT.PHTmessageOuterClass.Query getQuery() {
      return query_;
    }
    /**
     * <code>optional .PHT.Query query = 3;</code>
     */
    public PHT.PHTmessageOuterClass.QueryOrBuilder getQueryOrBuilder() {
      return query_;
    }

    public static final int ANSWER_FIELD_NUMBER = 4;
    private PHT.PHTmessageOuterClass.Answer answer_;
    /**
     * <code>optional .PHT.Answer answer = 4;</code>
     *
     * <pre>
     *repeated Column column = 5;
     * </pre>
     */
    public boolean hasAnswer() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .PHT.Answer answer = 4;</code>
     *
     * <pre>
     *repeated Column column = 5;
     * </pre>
     */
    public PHT.PHTmessageOuterClass.Answer getAnswer() {
      return answer_;
    }
    /**
     * <code>optional .PHT.Answer answer = 4;</code>
     *
     * <pre>
     *repeated Column column = 5;
     * </pre>
     */
    public PHT.PHTmessageOuterClass.AnswerOrBuilder getAnswerOrBuilder() {
      return answer_;
    }

    private void initFields() {
      type_ = PHT.PHTmessageOuterClass.PHTmessage.MessageType.DATA;
      proposal_ = java.util.Collections.emptyList();
      query_ = PHT.PHTmessageOuterClass.Query.getDefaultInstance();
      answer_ = PHT.PHTmessageOuterClass.Answer.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      for (int i = 0; i < proposal_.size(); i++) {
        output.writeMessage(2, proposal_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, query_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(4, answer_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      for (int i = 0; i < proposal_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, proposal_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, query_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, answer_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.PHTmessageOuterClass.PHTmessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.PHTmessageOuterClass.PHTmessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.PHTmessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.PHTmessage)
        PHT.PHTmessageOuterClass.PHTmessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_PHTmessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_PHTmessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.PHTmessageOuterClass.PHTmessage.class, PHT.PHTmessageOuterClass.PHTmessage.Builder.class);
      }

      // Construct using PHT.PHTmessageOuterClass.PHTmessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProposalFieldBuilder();
          getQueryFieldBuilder();
          getAnswerFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = PHT.PHTmessageOuterClass.PHTmessage.MessageType.DATA;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (proposalBuilder_ == null) {
          proposal_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          proposalBuilder_.clear();
        }
        if (queryBuilder_ == null) {
          query_ = PHT.PHTmessageOuterClass.Query.getDefaultInstance();
        } else {
          queryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (answerBuilder_ == null) {
          answer_ = PHT.PHTmessageOuterClass.Answer.getDefaultInstance();
        } else {
          answerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.PHTmessageOuterClass.internal_static_PHT_PHTmessage_descriptor;
      }

      public PHT.PHTmessageOuterClass.PHTmessage getDefaultInstanceForType() {
        return PHT.PHTmessageOuterClass.PHTmessage.getDefaultInstance();
      }

      public PHT.PHTmessageOuterClass.PHTmessage build() {
        PHT.PHTmessageOuterClass.PHTmessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.PHTmessageOuterClass.PHTmessage buildPartial() {
        PHT.PHTmessageOuterClass.PHTmessage result = new PHT.PHTmessageOuterClass.PHTmessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (proposalBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            proposal_ = java.util.Collections.unmodifiableList(proposal_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.proposal_ = proposal_;
        } else {
          result.proposal_ = proposalBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (queryBuilder_ == null) {
          result.query_ = query_;
        } else {
          result.query_ = queryBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        if (answerBuilder_ == null) {
          result.answer_ = answer_;
        } else {
          result.answer_ = answerBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.PHTmessageOuterClass.PHTmessage) {
          return mergeFrom((PHT.PHTmessageOuterClass.PHTmessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.PHTmessageOuterClass.PHTmessage other) {
        if (other == PHT.PHTmessageOuterClass.PHTmessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (proposalBuilder_ == null) {
          if (!other.proposal_.isEmpty()) {
            if (proposal_.isEmpty()) {
              proposal_ = other.proposal_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureProposalIsMutable();
              proposal_.addAll(other.proposal_);
            }
            onChanged();
          }
        } else {
          if (!other.proposal_.isEmpty()) {
            if (proposalBuilder_.isEmpty()) {
              proposalBuilder_.dispose();
              proposalBuilder_ = null;
              proposal_ = other.proposal_;
              bitField0_ = (bitField0_ & ~0x00000002);
              proposalBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProposalFieldBuilder() : null;
            } else {
              proposalBuilder_.addAllMessages(other.proposal_);
            }
          }
        }
        if (other.hasQuery()) {
          mergeQuery(other.getQuery());
        }
        if (other.hasAnswer()) {
          mergeAnswer(other.getAnswer());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.PHTmessageOuterClass.PHTmessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.PHTmessageOuterClass.PHTmessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private PHT.PHTmessageOuterClass.PHTmessage.MessageType type_ = PHT.PHTmessageOuterClass.PHTmessage.MessageType.DATA;
      /**
       * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
       */
      public PHT.PHTmessageOuterClass.PHTmessage.MessageType getType() {
        return type_;
      }
      /**
       * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
       */
      public Builder setType(PHT.PHTmessageOuterClass.PHTmessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .PHT.PHTmessage.MessageType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = PHT.PHTmessageOuterClass.PHTmessage.MessageType.DATA;
        onChanged();
        return this;
      }

      private java.util.List<PHT.ProposalsOuterClass.Proposals> proposal_ =
        java.util.Collections.emptyList();
      private void ensureProposalIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          proposal_ = new java.util.ArrayList<PHT.ProposalsOuterClass.Proposals>(proposal_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PHT.ProposalsOuterClass.Proposals, PHT.ProposalsOuterClass.Proposals.Builder, PHT.ProposalsOuterClass.ProposalsOrBuilder> proposalBuilder_;

      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public java.util.List<PHT.ProposalsOuterClass.Proposals> getProposalList() {
        if (proposalBuilder_ == null) {
          return java.util.Collections.unmodifiableList(proposal_);
        } else {
          return proposalBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public int getProposalCount() {
        if (proposalBuilder_ == null) {
          return proposal_.size();
        } else {
          return proposalBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public PHT.ProposalsOuterClass.Proposals getProposal(int index) {
        if (proposalBuilder_ == null) {
          return proposal_.get(index);
        } else {
          return proposalBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder setProposal(
          int index, PHT.ProposalsOuterClass.Proposals value) {
        if (proposalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProposalIsMutable();
          proposal_.set(index, value);
          onChanged();
        } else {
          proposalBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder setProposal(
          int index, PHT.ProposalsOuterClass.Proposals.Builder builderForValue) {
        if (proposalBuilder_ == null) {
          ensureProposalIsMutable();
          proposal_.set(index, builderForValue.build());
          onChanged();
        } else {
          proposalBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder addProposal(PHT.ProposalsOuterClass.Proposals value) {
        if (proposalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProposalIsMutable();
          proposal_.add(value);
          onChanged();
        } else {
          proposalBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder addProposal(
          int index, PHT.ProposalsOuterClass.Proposals value) {
        if (proposalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProposalIsMutable();
          proposal_.add(index, value);
          onChanged();
        } else {
          proposalBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder addProposal(
          PHT.ProposalsOuterClass.Proposals.Builder builderForValue) {
        if (proposalBuilder_ == null) {
          ensureProposalIsMutable();
          proposal_.add(builderForValue.build());
          onChanged();
        } else {
          proposalBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder addProposal(
          int index, PHT.ProposalsOuterClass.Proposals.Builder builderForValue) {
        if (proposalBuilder_ == null) {
          ensureProposalIsMutable();
          proposal_.add(index, builderForValue.build());
          onChanged();
        } else {
          proposalBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder addAllProposal(
          java.lang.Iterable<? extends PHT.ProposalsOuterClass.Proposals> values) {
        if (proposalBuilder_ == null) {
          ensureProposalIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, proposal_);
          onChanged();
        } else {
          proposalBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder clearProposal() {
        if (proposalBuilder_ == null) {
          proposal_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          proposalBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public Builder removeProposal(int index) {
        if (proposalBuilder_ == null) {
          ensureProposalIsMutable();
          proposal_.remove(index);
          onChanged();
        } else {
          proposalBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public PHT.ProposalsOuterClass.Proposals.Builder getProposalBuilder(
          int index) {
        return getProposalFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public PHT.ProposalsOuterClass.ProposalsOrBuilder getProposalOrBuilder(
          int index) {
        if (proposalBuilder_ == null) {
          return proposal_.get(index);  } else {
          return proposalBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public java.util.List<? extends PHT.ProposalsOuterClass.ProposalsOrBuilder> 
           getProposalOrBuilderList() {
        if (proposalBuilder_ != null) {
          return proposalBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(proposal_);
        }
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public PHT.ProposalsOuterClass.Proposals.Builder addProposalBuilder() {
        return getProposalFieldBuilder().addBuilder(
            PHT.ProposalsOuterClass.Proposals.getDefaultInstance());
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public PHT.ProposalsOuterClass.Proposals.Builder addProposalBuilder(
          int index) {
        return getProposalFieldBuilder().addBuilder(
            index, PHT.ProposalsOuterClass.Proposals.getDefaultInstance());
      }
      /**
       * <code>repeated .PHT.Proposals proposal = 2;</code>
       *
       * <pre>
       *optional Proposals proposal = 2;
       * </pre>
       */
      public java.util.List<PHT.ProposalsOuterClass.Proposals.Builder> 
           getProposalBuilderList() {
        return getProposalFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PHT.ProposalsOuterClass.Proposals, PHT.ProposalsOuterClass.Proposals.Builder, PHT.ProposalsOuterClass.ProposalsOrBuilder> 
          getProposalFieldBuilder() {
        if (proposalBuilder_ == null) {
          proposalBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PHT.ProposalsOuterClass.Proposals, PHT.ProposalsOuterClass.Proposals.Builder, PHT.ProposalsOuterClass.ProposalsOrBuilder>(
                  proposal_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          proposal_ = null;
        }
        return proposalBuilder_;
      }

      private PHT.PHTmessageOuterClass.Query query_ = PHT.PHTmessageOuterClass.Query.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          PHT.PHTmessageOuterClass.Query, PHT.PHTmessageOuterClass.Query.Builder, PHT.PHTmessageOuterClass.QueryOrBuilder> queryBuilder_;
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public boolean hasQuery() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public PHT.PHTmessageOuterClass.Query getQuery() {
        if (queryBuilder_ == null) {
          return query_;
        } else {
          return queryBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public Builder setQuery(PHT.PHTmessageOuterClass.Query value) {
        if (queryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          query_ = value;
          onChanged();
        } else {
          queryBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public Builder setQuery(
          PHT.PHTmessageOuterClass.Query.Builder builderForValue) {
        if (queryBuilder_ == null) {
          query_ = builderForValue.build();
          onChanged();
        } else {
          queryBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public Builder mergeQuery(PHT.PHTmessageOuterClass.Query value) {
        if (queryBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              query_ != PHT.PHTmessageOuterClass.Query.getDefaultInstance()) {
            query_ =
              PHT.PHTmessageOuterClass.Query.newBuilder(query_).mergeFrom(value).buildPartial();
          } else {
            query_ = value;
          }
          onChanged();
        } else {
          queryBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public Builder clearQuery() {
        if (queryBuilder_ == null) {
          query_ = PHT.PHTmessageOuterClass.Query.getDefaultInstance();
          onChanged();
        } else {
          queryBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public PHT.PHTmessageOuterClass.Query.Builder getQueryBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getQueryFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      public PHT.PHTmessageOuterClass.QueryOrBuilder getQueryOrBuilder() {
        if (queryBuilder_ != null) {
          return queryBuilder_.getMessageOrBuilder();
        } else {
          return query_;
        }
      }
      /**
       * <code>optional .PHT.Query query = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          PHT.PHTmessageOuterClass.Query, PHT.PHTmessageOuterClass.Query.Builder, PHT.PHTmessageOuterClass.QueryOrBuilder> 
          getQueryFieldBuilder() {
        if (queryBuilder_ == null) {
          queryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              PHT.PHTmessageOuterClass.Query, PHT.PHTmessageOuterClass.Query.Builder, PHT.PHTmessageOuterClass.QueryOrBuilder>(
                  getQuery(),
                  getParentForChildren(),
                  isClean());
          query_ = null;
        }
        return queryBuilder_;
      }

      private PHT.PHTmessageOuterClass.Answer answer_ = PHT.PHTmessageOuterClass.Answer.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          PHT.PHTmessageOuterClass.Answer, PHT.PHTmessageOuterClass.Answer.Builder, PHT.PHTmessageOuterClass.AnswerOrBuilder> answerBuilder_;
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public boolean hasAnswer() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public PHT.PHTmessageOuterClass.Answer getAnswer() {
        if (answerBuilder_ == null) {
          return answer_;
        } else {
          return answerBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public Builder setAnswer(PHT.PHTmessageOuterClass.Answer value) {
        if (answerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          answer_ = value;
          onChanged();
        } else {
          answerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public Builder setAnswer(
          PHT.PHTmessageOuterClass.Answer.Builder builderForValue) {
        if (answerBuilder_ == null) {
          answer_ = builderForValue.build();
          onChanged();
        } else {
          answerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public Builder mergeAnswer(PHT.PHTmessageOuterClass.Answer value) {
        if (answerBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              answer_ != PHT.PHTmessageOuterClass.Answer.getDefaultInstance()) {
            answer_ =
              PHT.PHTmessageOuterClass.Answer.newBuilder(answer_).mergeFrom(value).buildPartial();
          } else {
            answer_ = value;
          }
          onChanged();
        } else {
          answerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public Builder clearAnswer() {
        if (answerBuilder_ == null) {
          answer_ = PHT.PHTmessageOuterClass.Answer.getDefaultInstance();
          onChanged();
        } else {
          answerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public PHT.PHTmessageOuterClass.Answer.Builder getAnswerBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAnswerFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      public PHT.PHTmessageOuterClass.AnswerOrBuilder getAnswerOrBuilder() {
        if (answerBuilder_ != null) {
          return answerBuilder_.getMessageOrBuilder();
        } else {
          return answer_;
        }
      }
      /**
       * <code>optional .PHT.Answer answer = 4;</code>
       *
       * <pre>
       *repeated Column column = 5;
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          PHT.PHTmessageOuterClass.Answer, PHT.PHTmessageOuterClass.Answer.Builder, PHT.PHTmessageOuterClass.AnswerOrBuilder> 
          getAnswerFieldBuilder() {
        if (answerBuilder_ == null) {
          answerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              PHT.PHTmessageOuterClass.Answer, PHT.PHTmessageOuterClass.Answer.Builder, PHT.PHTmessageOuterClass.AnswerOrBuilder>(
                  getAnswer(),
                  getParentForChildren(),
                  isClean());
          answer_ = null;
        }
        return answerBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:PHT.PHTmessage)
    }

    static {
      defaultInstance = new PHTmessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.PHTmessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_Answer_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_Answer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_Query_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_Query_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_PHTmessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_PHTmessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020PHTmessage.proto\022\003PHT\032\017Proposals.proto" +
      "\"\030\n\006Answer\022\016\n\006answer\030\001 \001(\t\"w\n\005Query\022\r\n\005q" +
      "uery\030\001 \001(\003\022\035\n\016file_to_upload\030\002 \001(\010:\005fals" +
      "e\022\021\n\tfile_name\030\003 \001(\t\022\021\n\tfile_data\030\004 \001(\014\022" +
      "\032\n\013delete_file\030\005 \001(\010:\005false\"\325\001\n\nPHTmessa" +
      "ge\022)\n\004type\030\001 \002(\0162\033.PHT.PHTmessage.Messag" +
      "eType\022 \n\010proposal\030\002 \003(\0132\016.PHT.Proposals\022" +
      "\031\n\005query\030\003 \001(\0132\n.PHT.Query\022\033\n\006answer\030\004 \001" +
      "(\0132\013.PHT.Answer\"B\n\013MessageType\022\010\n\004DATA\020\001" +
      "\022\t\n\005QUERY\020\002\022\n\n\006ANSWER\020\003\022\t\n\005ERROR\020\004\022\007\n\003PS",
      "T\020\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          PHT.ProposalsOuterClass.getDescriptor(),
        }, assigner);
    internal_static_PHT_Answer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PHT_Answer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_Answer_descriptor,
        new java.lang.String[] { "Answer", });
    internal_static_PHT_Query_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PHT_Query_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_Query_descriptor,
        new java.lang.String[] { "Query", "FileToUpload", "FileName", "FileData", "DeleteFile", });
    internal_static_PHT_PHTmessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PHT_PHTmessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_PHTmessage_descriptor,
        new java.lang.String[] { "Type", "Proposal", "Query", "Answer", });
    PHT.ProposalsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
