// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ScienceGoals.proto

package PHT;

public final class ScienceGoalsOuterClass {
  private ScienceGoalsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ScienceGoalsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.ScienceGoals)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double frequence = 1;</code>
     */
    boolean hasFrequence();
    /**
     * <code>optional double frequence = 1;</code>
     */
    double getFrequence();

    /**
     * <code>optional string instrument_configurations = 2;</code>
     */
    boolean hasInstrumentConfigurations();
    /**
     * <code>optional string instrument_configurations = 2;</code>
     */
    java.lang.String getInstrumentConfigurations();
    /**
     * <code>optional string instrument_configurations = 2;</code>
     */
    com.google.protobuf.ByteString
        getInstrumentConfigurationsBytes();

    /**
     * <code>optional string more_info = 3;</code>
     */
    boolean hasMoreInfo();
    /**
     * <code>optional string more_info = 3;</code>
     */
    java.lang.String getMoreInfo();
    /**
     * <code>optional string more_info = 3;</code>
     */
    com.google.protobuf.ByteString
        getMoreInfoBytes();

    /**
     * <code>optional string target_details = 4;</code>
     */
    boolean hasTargetDetails();
    /**
     * <code>optional string target_details = 4;</code>
     */
    java.lang.String getTargetDetails();
    /**
     * <code>optional string target_details = 4;</code>
     */
    com.google.protobuf.ByteString
        getTargetDetailsBytes();
  }
  /**
   * Protobuf type {@code PHT.ScienceGoals}
   */
  public static final class ScienceGoals extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.ScienceGoals)
      ScienceGoalsOrBuilder {
    // Use ScienceGoals.newBuilder() to construct.
    private ScienceGoals(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ScienceGoals(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ScienceGoals defaultInstance;
    public static ScienceGoals getDefaultInstance() {
      return defaultInstance;
    }

    public ScienceGoals getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ScienceGoals(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              frequence_ = input.readDouble();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              instrumentConfigurations_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              moreInfo_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              targetDetails_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.ScienceGoalsOuterClass.internal_static_PHT_ScienceGoals_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.ScienceGoalsOuterClass.internal_static_PHT_ScienceGoals_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.ScienceGoalsOuterClass.ScienceGoals.class, PHT.ScienceGoalsOuterClass.ScienceGoals.Builder.class);
    }

    public static com.google.protobuf.Parser<ScienceGoals> PARSER =
        new com.google.protobuf.AbstractParser<ScienceGoals>() {
      public ScienceGoals parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScienceGoals(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ScienceGoals> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int FREQUENCE_FIELD_NUMBER = 1;
    private double frequence_;
    /**
     * <code>optional double frequence = 1;</code>
     */
    public boolean hasFrequence() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double frequence = 1;</code>
     */
    public double getFrequence() {
      return frequence_;
    }

    public static final int INSTRUMENT_CONFIGURATIONS_FIELD_NUMBER = 2;
    private java.lang.Object instrumentConfigurations_;
    /**
     * <code>optional string instrument_configurations = 2;</code>
     */
    public boolean hasInstrumentConfigurations() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string instrument_configurations = 2;</code>
     */
    public java.lang.String getInstrumentConfigurations() {
      java.lang.Object ref = instrumentConfigurations_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          instrumentConfigurations_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string instrument_configurations = 2;</code>
     */
    public com.google.protobuf.ByteString
        getInstrumentConfigurationsBytes() {
      java.lang.Object ref = instrumentConfigurations_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumentConfigurations_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MORE_INFO_FIELD_NUMBER = 3;
    private java.lang.Object moreInfo_;
    /**
     * <code>optional string more_info = 3;</code>
     */
    public boolean hasMoreInfo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string more_info = 3;</code>
     */
    public java.lang.String getMoreInfo() {
      java.lang.Object ref = moreInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          moreInfo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string more_info = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMoreInfoBytes() {
      java.lang.Object ref = moreInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        moreInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGET_DETAILS_FIELD_NUMBER = 4;
    private java.lang.Object targetDetails_;
    /**
     * <code>optional string target_details = 4;</code>
     */
    public boolean hasTargetDetails() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string target_details = 4;</code>
     */
    public java.lang.String getTargetDetails() {
      java.lang.Object ref = targetDetails_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          targetDetails_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string target_details = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTargetDetailsBytes() {
      java.lang.Object ref = targetDetails_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        targetDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      frequence_ = 0D;
      instrumentConfigurations_ = "";
      moreInfo_ = "";
      targetDetails_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, frequence_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getInstrumentConfigurationsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getMoreInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getTargetDetailsBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, frequence_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getInstrumentConfigurationsBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getMoreInfoBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getTargetDetailsBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.ScienceGoalsOuterClass.ScienceGoals parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.ScienceGoalsOuterClass.ScienceGoals prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.ScienceGoals}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.ScienceGoals)
        PHT.ScienceGoalsOuterClass.ScienceGoalsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.ScienceGoalsOuterClass.internal_static_PHT_ScienceGoals_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.ScienceGoalsOuterClass.internal_static_PHT_ScienceGoals_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.ScienceGoalsOuterClass.ScienceGoals.class, PHT.ScienceGoalsOuterClass.ScienceGoals.Builder.class);
      }

      // Construct using PHT.ScienceGoalsOuterClass.ScienceGoals.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        frequence_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        instrumentConfigurations_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        moreInfo_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        targetDetails_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.ScienceGoalsOuterClass.internal_static_PHT_ScienceGoals_descriptor;
      }

      public PHT.ScienceGoalsOuterClass.ScienceGoals getDefaultInstanceForType() {
        return PHT.ScienceGoalsOuterClass.ScienceGoals.getDefaultInstance();
      }

      public PHT.ScienceGoalsOuterClass.ScienceGoals build() {
        PHT.ScienceGoalsOuterClass.ScienceGoals result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.ScienceGoalsOuterClass.ScienceGoals buildPartial() {
        PHT.ScienceGoalsOuterClass.ScienceGoals result = new PHT.ScienceGoalsOuterClass.ScienceGoals(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.frequence_ = frequence_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.instrumentConfigurations_ = instrumentConfigurations_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.moreInfo_ = moreInfo_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.targetDetails_ = targetDetails_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.ScienceGoalsOuterClass.ScienceGoals) {
          return mergeFrom((PHT.ScienceGoalsOuterClass.ScienceGoals)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.ScienceGoalsOuterClass.ScienceGoals other) {
        if (other == PHT.ScienceGoalsOuterClass.ScienceGoals.getDefaultInstance()) return this;
        if (other.hasFrequence()) {
          setFrequence(other.getFrequence());
        }
        if (other.hasInstrumentConfigurations()) {
          bitField0_ |= 0x00000002;
          instrumentConfigurations_ = other.instrumentConfigurations_;
          onChanged();
        }
        if (other.hasMoreInfo()) {
          bitField0_ |= 0x00000004;
          moreInfo_ = other.moreInfo_;
          onChanged();
        }
        if (other.hasTargetDetails()) {
          bitField0_ |= 0x00000008;
          targetDetails_ = other.targetDetails_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.ScienceGoalsOuterClass.ScienceGoals parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.ScienceGoalsOuterClass.ScienceGoals) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double frequence_ ;
      /**
       * <code>optional double frequence = 1;</code>
       */
      public boolean hasFrequence() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double frequence = 1;</code>
       */
      public double getFrequence() {
        return frequence_;
      }
      /**
       * <code>optional double frequence = 1;</code>
       */
      public Builder setFrequence(double value) {
        bitField0_ |= 0x00000001;
        frequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double frequence = 1;</code>
       */
      public Builder clearFrequence() {
        bitField0_ = (bitField0_ & ~0x00000001);
        frequence_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object instrumentConfigurations_ = "";
      /**
       * <code>optional string instrument_configurations = 2;</code>
       */
      public boolean hasInstrumentConfigurations() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string instrument_configurations = 2;</code>
       */
      public java.lang.String getInstrumentConfigurations() {
        java.lang.Object ref = instrumentConfigurations_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            instrumentConfigurations_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string instrument_configurations = 2;</code>
       */
      public com.google.protobuf.ByteString
          getInstrumentConfigurationsBytes() {
        java.lang.Object ref = instrumentConfigurations_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          instrumentConfigurations_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string instrument_configurations = 2;</code>
       */
      public Builder setInstrumentConfigurations(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        instrumentConfigurations_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string instrument_configurations = 2;</code>
       */
      public Builder clearInstrumentConfigurations() {
        bitField0_ = (bitField0_ & ~0x00000002);
        instrumentConfigurations_ = getDefaultInstance().getInstrumentConfigurations();
        onChanged();
        return this;
      }
      /**
       * <code>optional string instrument_configurations = 2;</code>
       */
      public Builder setInstrumentConfigurationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        instrumentConfigurations_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object moreInfo_ = "";
      /**
       * <code>optional string more_info = 3;</code>
       */
      public boolean hasMoreInfo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string more_info = 3;</code>
       */
      public java.lang.String getMoreInfo() {
        java.lang.Object ref = moreInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            moreInfo_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string more_info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMoreInfoBytes() {
        java.lang.Object ref = moreInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          moreInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string more_info = 3;</code>
       */
      public Builder setMoreInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        moreInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string more_info = 3;</code>
       */
      public Builder clearMoreInfo() {
        bitField0_ = (bitField0_ & ~0x00000004);
        moreInfo_ = getDefaultInstance().getMoreInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string more_info = 3;</code>
       */
      public Builder setMoreInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        moreInfo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object targetDetails_ = "";
      /**
       * <code>optional string target_details = 4;</code>
       */
      public boolean hasTargetDetails() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string target_details = 4;</code>
       */
      public java.lang.String getTargetDetails() {
        java.lang.Object ref = targetDetails_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            targetDetails_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string target_details = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTargetDetailsBytes() {
        java.lang.Object ref = targetDetails_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          targetDetails_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string target_details = 4;</code>
       */
      public Builder setTargetDetails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        targetDetails_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string target_details = 4;</code>
       */
      public Builder clearTargetDetails() {
        bitField0_ = (bitField0_ & ~0x00000008);
        targetDetails_ = getDefaultInstance().getTargetDetails();
        onChanged();
        return this;
      }
      /**
       * <code>optional string target_details = 4;</code>
       */
      public Builder setTargetDetailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        targetDetails_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PHT.ScienceGoals)
    }

    static {
      defaultInstance = new ScienceGoals(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.ScienceGoals)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_ScienceGoals_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_ScienceGoals_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022ScienceGoals.proto\022\003PHT\"o\n\014ScienceGoal" +
      "s\022\021\n\tfrequence\030\001 \001(\001\022!\n\031instrument_confi" +
      "gurations\030\002 \001(\t\022\021\n\tmore_info\030\003 \001(\t\022\026\n\016ta" +
      "rget_details\030\004 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PHT_ScienceGoals_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PHT_ScienceGoals_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_ScienceGoals_descriptor,
        new java.lang.String[] { "Frequence", "InstrumentConfigurations", "MoreInfo", "TargetDetails", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
