// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SupportingDocuments.proto

package PHT;

public final class SupportingDocumentsOuterClass {
  private SupportingDocumentsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SupportingDocumentsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PHT.SupportingDocuments)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string preprints = 1;</code>
     */
    boolean hasPreprints();
    /**
     * <code>optional string preprints = 1;</code>
     */
    java.lang.String getPreprints();
    /**
     * <code>optional string preprints = 1;</code>
     */
    com.google.protobuf.ByteString
        getPreprintsBytes();

    /**
     * <code>optional string scientific_justification = 2;</code>
     */
    boolean hasScientificJustification();
    /**
     * <code>optional string scientific_justification = 2;</code>
     */
    java.lang.String getScientificJustification();
    /**
     * <code>optional string scientific_justification = 2;</code>
     */
    com.google.protobuf.ByteString
        getScientificJustificationBytes();

    /**
     * <code>optional string technical_justification = 3;</code>
     */
    boolean hasTechnicalJustification();
    /**
     * <code>optional string technical_justification = 3;</code>
     */
    java.lang.String getTechnicalJustification();
    /**
     * <code>optional string technical_justification = 3;</code>
     */
    com.google.protobuf.ByteString
        getTechnicalJustificationBytes();
  }
  /**
   * Protobuf type {@code PHT.SupportingDocuments}
   */
  public static final class SupportingDocuments extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PHT.SupportingDocuments)
      SupportingDocumentsOrBuilder {
    // Use SupportingDocuments.newBuilder() to construct.
    private SupportingDocuments(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SupportingDocuments(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SupportingDocuments defaultInstance;
    public static SupportingDocuments getDefaultInstance() {
      return defaultInstance;
    }

    public SupportingDocuments getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SupportingDocuments(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              preprints_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              scientificJustification_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              technicalJustification_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PHT.SupportingDocumentsOuterClass.internal_static_PHT_SupportingDocuments_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PHT.SupportingDocumentsOuterClass.internal_static_PHT_SupportingDocuments_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PHT.SupportingDocumentsOuterClass.SupportingDocuments.class, PHT.SupportingDocumentsOuterClass.SupportingDocuments.Builder.class);
    }

    public static com.google.protobuf.Parser<SupportingDocuments> PARSER =
        new com.google.protobuf.AbstractParser<SupportingDocuments>() {
      public SupportingDocuments parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SupportingDocuments(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SupportingDocuments> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PREPRINTS_FIELD_NUMBER = 1;
    private java.lang.Object preprints_;
    /**
     * <code>optional string preprints = 1;</code>
     */
    public boolean hasPreprints() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string preprints = 1;</code>
     */
    public java.lang.String getPreprints() {
      java.lang.Object ref = preprints_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          preprints_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string preprints = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPreprintsBytes() {
      java.lang.Object ref = preprints_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        preprints_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCIENTIFIC_JUSTIFICATION_FIELD_NUMBER = 2;
    private java.lang.Object scientificJustification_;
    /**
     * <code>optional string scientific_justification = 2;</code>
     */
    public boolean hasScientificJustification() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string scientific_justification = 2;</code>
     */
    public java.lang.String getScientificJustification() {
      java.lang.Object ref = scientificJustification_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          scientificJustification_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string scientific_justification = 2;</code>
     */
    public com.google.protobuf.ByteString
        getScientificJustificationBytes() {
      java.lang.Object ref = scientificJustification_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scientificJustification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TECHNICAL_JUSTIFICATION_FIELD_NUMBER = 3;
    private java.lang.Object technicalJustification_;
    /**
     * <code>optional string technical_justification = 3;</code>
     */
    public boolean hasTechnicalJustification() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string technical_justification = 3;</code>
     */
    public java.lang.String getTechnicalJustification() {
      java.lang.Object ref = technicalJustification_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          technicalJustification_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string technical_justification = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTechnicalJustificationBytes() {
      java.lang.Object ref = technicalJustification_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        technicalJustification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      preprints_ = "";
      scientificJustification_ = "";
      technicalJustification_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPreprintsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getScientificJustificationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTechnicalJustificationBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPreprintsBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getScientificJustificationBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTechnicalJustificationBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PHT.SupportingDocumentsOuterClass.SupportingDocuments parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PHT.SupportingDocumentsOuterClass.SupportingDocuments prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PHT.SupportingDocuments}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PHT.SupportingDocuments)
        PHT.SupportingDocumentsOuterClass.SupportingDocumentsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PHT.SupportingDocumentsOuterClass.internal_static_PHT_SupportingDocuments_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PHT.SupportingDocumentsOuterClass.internal_static_PHT_SupportingDocuments_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PHT.SupportingDocumentsOuterClass.SupportingDocuments.class, PHT.SupportingDocumentsOuterClass.SupportingDocuments.Builder.class);
      }

      // Construct using PHT.SupportingDocumentsOuterClass.SupportingDocuments.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        preprints_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        scientificJustification_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        technicalJustification_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PHT.SupportingDocumentsOuterClass.internal_static_PHT_SupportingDocuments_descriptor;
      }

      public PHT.SupportingDocumentsOuterClass.SupportingDocuments getDefaultInstanceForType() {
        return PHT.SupportingDocumentsOuterClass.SupportingDocuments.getDefaultInstance();
      }

      public PHT.SupportingDocumentsOuterClass.SupportingDocuments build() {
        PHT.SupportingDocumentsOuterClass.SupportingDocuments result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PHT.SupportingDocumentsOuterClass.SupportingDocuments buildPartial() {
        PHT.SupportingDocumentsOuterClass.SupportingDocuments result = new PHT.SupportingDocumentsOuterClass.SupportingDocuments(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.preprints_ = preprints_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.scientificJustification_ = scientificJustification_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.technicalJustification_ = technicalJustification_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PHT.SupportingDocumentsOuterClass.SupportingDocuments) {
          return mergeFrom((PHT.SupportingDocumentsOuterClass.SupportingDocuments)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PHT.SupportingDocumentsOuterClass.SupportingDocuments other) {
        if (other == PHT.SupportingDocumentsOuterClass.SupportingDocuments.getDefaultInstance()) return this;
        if (other.hasPreprints()) {
          bitField0_ |= 0x00000001;
          preprints_ = other.preprints_;
          onChanged();
        }
        if (other.hasScientificJustification()) {
          bitField0_ |= 0x00000002;
          scientificJustification_ = other.scientificJustification_;
          onChanged();
        }
        if (other.hasTechnicalJustification()) {
          bitField0_ |= 0x00000004;
          technicalJustification_ = other.technicalJustification_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PHT.SupportingDocumentsOuterClass.SupportingDocuments parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PHT.SupportingDocumentsOuterClass.SupportingDocuments) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object preprints_ = "";
      /**
       * <code>optional string preprints = 1;</code>
       */
      public boolean hasPreprints() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string preprints = 1;</code>
       */
      public java.lang.String getPreprints() {
        java.lang.Object ref = preprints_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            preprints_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string preprints = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPreprintsBytes() {
        java.lang.Object ref = preprints_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          preprints_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string preprints = 1;</code>
       */
      public Builder setPreprints(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        preprints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string preprints = 1;</code>
       */
      public Builder clearPreprints() {
        bitField0_ = (bitField0_ & ~0x00000001);
        preprints_ = getDefaultInstance().getPreprints();
        onChanged();
        return this;
      }
      /**
       * <code>optional string preprints = 1;</code>
       */
      public Builder setPreprintsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        preprints_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object scientificJustification_ = "";
      /**
       * <code>optional string scientific_justification = 2;</code>
       */
      public boolean hasScientificJustification() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string scientific_justification = 2;</code>
       */
      public java.lang.String getScientificJustification() {
        java.lang.Object ref = scientificJustification_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            scientificJustification_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string scientific_justification = 2;</code>
       */
      public com.google.protobuf.ByteString
          getScientificJustificationBytes() {
        java.lang.Object ref = scientificJustification_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          scientificJustification_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string scientific_justification = 2;</code>
       */
      public Builder setScientificJustification(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        scientificJustification_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string scientific_justification = 2;</code>
       */
      public Builder clearScientificJustification() {
        bitField0_ = (bitField0_ & ~0x00000002);
        scientificJustification_ = getDefaultInstance().getScientificJustification();
        onChanged();
        return this;
      }
      /**
       * <code>optional string scientific_justification = 2;</code>
       */
      public Builder setScientificJustificationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        scientificJustification_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object technicalJustification_ = "";
      /**
       * <code>optional string technical_justification = 3;</code>
       */
      public boolean hasTechnicalJustification() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string technical_justification = 3;</code>
       */
      public java.lang.String getTechnicalJustification() {
        java.lang.Object ref = technicalJustification_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            technicalJustification_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string technical_justification = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTechnicalJustificationBytes() {
        java.lang.Object ref = technicalJustification_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          technicalJustification_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string technical_justification = 3;</code>
       */
      public Builder setTechnicalJustification(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        technicalJustification_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string technical_justification = 3;</code>
       */
      public Builder clearTechnicalJustification() {
        bitField0_ = (bitField0_ & ~0x00000004);
        technicalJustification_ = getDefaultInstance().getTechnicalJustification();
        onChanged();
        return this;
      }
      /**
       * <code>optional string technical_justification = 3;</code>
       */
      public Builder setTechnicalJustificationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        technicalJustification_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PHT.SupportingDocuments)
    }

    static {
      defaultInstance = new SupportingDocuments(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PHT.SupportingDocuments)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PHT_SupportingDocuments_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PHT_SupportingDocuments_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031SupportingDocuments.proto\022\003PHT\"k\n\023Supp" +
      "ortingDocuments\022\021\n\tpreprints\030\001 \001(\t\022 \n\030sc" +
      "ientific_justification\030\002 \001(\t\022\037\n\027technica" +
      "l_justification\030\003 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PHT_SupportingDocuments_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PHT_SupportingDocuments_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PHT_SupportingDocuments_descriptor,
        new java.lang.String[] { "Preprints", "ScientificJustification", "TechnicalJustification", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
