// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CoAuthors.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "CoAuthors.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace PHT {

namespace {

const ::google::protobuf::Descriptor* CoAuthors_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CoAuthors_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_CoAuthors_2eproto() {
  protobuf_AddDesc_CoAuthors_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "CoAuthors.proto");
  GOOGLE_CHECK(file != NULL);
  CoAuthors_descriptor_ = file->message_type(0);
  static const int CoAuthors_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CoAuthors, author_id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CoAuthors, proposal_id_),
  };
  CoAuthors_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      CoAuthors_descriptor_,
      CoAuthors::default_instance_,
      CoAuthors_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CoAuthors, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CoAuthors, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(CoAuthors));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_CoAuthors_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    CoAuthors_descriptor_, &CoAuthors::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_CoAuthors_2eproto() {
  delete CoAuthors::default_instance_;
  delete CoAuthors_reflection_;
}

void protobuf_AddDesc_CoAuthors_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017CoAuthors.proto\022\003PHT\"3\n\tCoAuthors\022\021\n\ta"
    "uthor_id\030\001 \001(\003\022\023\n\013proposal_id\030\002 \001(\003", 75);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CoAuthors.proto", &protobuf_RegisterTypes);
  CoAuthors::default_instance_ = new CoAuthors();
  CoAuthors::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_CoAuthors_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_CoAuthors_2eproto {
  StaticDescriptorInitializer_CoAuthors_2eproto() {
    protobuf_AddDesc_CoAuthors_2eproto();
  }
} static_descriptor_initializer_CoAuthors_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int CoAuthors::kAuthorIdFieldNumber;
const int CoAuthors::kProposalIdFieldNumber;
#endif  // !_MSC_VER

CoAuthors::CoAuthors()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PHT.CoAuthors)
}

void CoAuthors::InitAsDefaultInstance() {
}

CoAuthors::CoAuthors(const CoAuthors& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PHT.CoAuthors)
}

void CoAuthors::SharedCtor() {
  _cached_size_ = 0;
  author_id_ = GOOGLE_LONGLONG(0);
  proposal_id_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CoAuthors::~CoAuthors() {
  // @@protoc_insertion_point(destructor:PHT.CoAuthors)
  SharedDtor();
}

void CoAuthors::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CoAuthors::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CoAuthors::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CoAuthors_descriptor_;
}

const CoAuthors& CoAuthors::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_CoAuthors_2eproto();
  return *default_instance_;
}

CoAuthors* CoAuthors::default_instance_ = NULL;

CoAuthors* CoAuthors::New() const {
  return new CoAuthors;
}

void CoAuthors::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<CoAuthors*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(author_id_, proposal_id_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool CoAuthors::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PHT.CoAuthors)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int64 author_id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &author_id_)));
          set_has_author_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_proposal_id;
        break;
      }

      // optional int64 proposal_id = 2;
      case 2: {
        if (tag == 16) {
         parse_proposal_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &proposal_id_)));
          set_has_proposal_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PHT.CoAuthors)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PHT.CoAuthors)
  return false;
#undef DO_
}

void CoAuthors::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PHT.CoAuthors)
  // optional int64 author_id = 1;
  if (has_author_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->author_id(), output);
  }

  // optional int64 proposal_id = 2;
  if (has_proposal_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->proposal_id(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PHT.CoAuthors)
}

::google::protobuf::uint8* CoAuthors::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PHT.CoAuthors)
  // optional int64 author_id = 1;
  if (has_author_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->author_id(), target);
  }

  // optional int64 proposal_id = 2;
  if (has_proposal_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->proposal_id(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PHT.CoAuthors)
  return target;
}

int CoAuthors::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int64 author_id = 1;
    if (has_author_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->author_id());
    }

    // optional int64 proposal_id = 2;
    if (has_proposal_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->proposal_id());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CoAuthors::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const CoAuthors* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const CoAuthors*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CoAuthors::MergeFrom(const CoAuthors& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_author_id()) {
      set_author_id(from.author_id());
    }
    if (from.has_proposal_id()) {
      set_proposal_id(from.proposal_id());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void CoAuthors::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CoAuthors::CopyFrom(const CoAuthors& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CoAuthors::IsInitialized() const {

  return true;
}

void CoAuthors::Swap(CoAuthors* other) {
  if (other != this) {
    std::swap(author_id_, other->author_id_);
    std::swap(proposal_id_, other->proposal_id_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata CoAuthors::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CoAuthors_descriptor_;
  metadata.reflection = CoAuthors_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace PHT

// @@protoc_insertion_point(global_scope)
