// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProposalStatus.proto

#ifndef PROTOBUF_ProposalStatus_2eproto__INCLUDED
#define PROTOBUF_ProposalStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace PHT {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ProposalStatus_2eproto();
void protobuf_AssignDesc_ProposalStatus_2eproto();
void protobuf_ShutdownFile_ProposalStatus_2eproto();


enum ProposalStatus {
  DRAFT = 0,
  ACCEPTED = 1,
  REJECTED = 2,
  SUBMITTED = 3,
  MERGED = 4
};
bool ProposalStatus_IsValid(int value);
const ProposalStatus ProposalStatus_MIN = DRAFT;
const ProposalStatus ProposalStatus_MAX = MERGED;
const int ProposalStatus_ARRAYSIZE = ProposalStatus_MAX + 1;

const ::google::protobuf::EnumDescriptor* ProposalStatus_descriptor();
inline const ::std::string& ProposalStatus_Name(ProposalStatus value) {
  return ::google::protobuf::internal::NameOfEnum(
    ProposalStatus_descriptor(), value);
}
inline bool ProposalStatus_Parse(
    const ::std::string& name, ProposalStatus* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ProposalStatus>(
    ProposalStatus_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace PHT

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::PHT::ProposalStatus> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::PHT::ProposalStatus>() {
  return ::PHT::ProposalStatus_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ProposalStatus_2eproto__INCLUDED
