/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 27-Aug-2015 2:37:15 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

CREATE DATABASE IF NOT EXISTS PHT;

USE PHT;

SET FOREIGN_KEY_CHECKS=0 ;

/* Drop Tables */

DROP TABLE IF EXISTS `TACReviews` CASCADE
;

DROP TABLE IF EXISTS `SupportingDocuments` CASCADE
;

DROP TABLE IF EXISTS `ScienceGoals` CASCADE
;

DROP TABLE IF EXISTS `Reviews` CASCADE
;

DROP TABLE IF EXISTS `Proposals` CASCADE
;

DROP TABLE IF EXISTS `ProposalEditors` CASCADE
;

DROP TABLE IF EXISTS `CoAuthors` CASCADE
;

/* Create Tables */

CREATE TABLE `TACReviews`
(
	`comments` VARCHAR(50) 	 NULL,
	`final_grade` VARCHAR(50) 	 NULL,
	`tac_id` INTEGER 	 NULL ,
	`tACReviewsID` INTEGER NOT NULL,
	`proposal_id` INTEGER 	 NULL,
	CONSTRAINT `PK_TACReviews` PRIMARY KEY (`tACReviewsID`)
)

;

CREATE TABLE `SupportingDocuments`
(
	`preprints` VARCHAR(50) 	 NULL,
	`scientific_justification` VARCHAR(50) 	 NULL,
	`technical_justification` VARCHAR(50) 	 NULL,
	`supportingDocumentsID` INTEGER NOT NULL,
	`proposal_id` INTEGER 	 NULL,
	CONSTRAINT `PK_SupportingDocuments` PRIMARY KEY (`supportingDocumentsID`)
)

;

CREATE TABLE `ScienceGoals`
(
	`frequence` REAL 	 NULL,
	`instrument_configurations` VARCHAR(50) 	 NULL,
	`more_info` VARCHAR(50) 	 NULL,
	`target_details` VARCHAR(50) 	 NULL,
	`scienceGoalsID` INTEGER NOT NULL,
	`proposal_id` INTEGER 	 NULL,
	CONSTRAINT `PK_ScienceGoals` PRIMARY KEY (`scienceGoalsID`)
)

;

CREATE TABLE `Reviews`
(
	`grade_rank` VARCHAR(50) 	 NULL,
	`proposal_id` INTEGER 	 NOT NULL,
	`review_comments` VARCHAR(50) 	 NULL,
	`reviewer_id` INTEGER 	 NULL,
	`reviewsID` INTEGER NOT NULL,
	CONSTRAINT `PK_Reviews` PRIMARY KEY (`reviewsID`)
)

;

CREATE TABLE `Proposals`
(
	`abstract` VARCHAR(50) 	 NULL,
	`more_info` VARCHAR(50) 	 NULL,
	`proposal_id` INTEGER 	 NOT NULL AUTO_INCREMENT,
	`proposal_status` ENUM('Draft','Accepted','Rejected','Submitted','Merged') 	 NULL,
	`proposal_type` ENUM('TOO','DDT','PI','KeyScienceProject') 	 NULL,
	CONSTRAINT `PK_Proposals` PRIMARY KEY (`proposal_id`)
)

;

CREATE TABLE `ProposalEditors`
(
	`author_id` VARCHAR(50) 	 NULL,
	`isPI` BOOL 	 NULL,
	`more_info` VARCHAR(50) 	 NULL,
	`proposal_id` INTEGER 	 NOT NULL,
	`proposalEditorsID` INTEGER NOT NULL,
	CONSTRAINT `PK_ProposalEditors` PRIMARY KEY (`proposalEditorsID`)
)

;

CREATE TABLE `CoAuthors`
(
	`author_id` INTEGER 	 NULL,
	`proposal_id` INTEGER 	 NOT NULL,
	`coAuthorsID` INTEGER NOT NULL,
	CONSTRAINT `PK_CoAuthors` PRIMARY KEY (`coAuthorsID`)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `TACReviews` 
 ADD CONSTRAINT `FK_TACReviews_Proposals`
	FOREIGN KEY (`proposal_id`) REFERENCES `Proposals` (`proposal_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `SupportingDocuments` 
 ADD CONSTRAINT `FK_SupportingDocuments_Proposals`
	FOREIGN KEY (`proposal_id`) REFERENCES `Proposals` (`proposal_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ScienceGoals` 
 ADD CONSTRAINT `FK_ScienceGoals_Proposals`
	FOREIGN KEY (`proposal_id`) REFERENCES `Proposals` (`proposal_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Reviews` 
 ADD CONSTRAINT `FK_Reviews_Proposals`
	FOREIGN KEY (`proposal_id`) REFERENCES `Proposals` (`proposal_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `ProposalEditors` 
 ADD CONSTRAINT `FK_ProposalEditors_Proposals`
	FOREIGN KEY (`proposal_id`) REFERENCES `Proposals` (`proposal_id`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `CoAuthors` 
 ADD CONSTRAINT `FK_CoAuthors_Proposals`
	FOREIGN KEY (`proposal_id`) REFERENCES `Proposals` (`proposal_id`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 ;
